# -------------------------------------------------------------------
# Sheldon Configuration
# -------------------------------------------------------------------
shell = "zsh"

[plugins]

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = '''
{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"
{% endfor %}{{ hooks?.post | nl }}'''
fzf-install = '''
{{ dir }}/install --bin > /dev/null 
path=($path {{ dir }}/bin(N-/))'''
fzf-source = "source <(fzf --zsh)"

# -------------------------------------------------------------------
# starship/starship
# -------------------------------------------------------------------
# [plugins.starship]
# inline = 'eval "$(starship init zsh)"'

# -------------------------------------------------------------------
# asdf-vm (asdf), pinned to v0.15.0
# -------------------------------------------------------------------
[plugins.asdf]
github = "asdf-vm/asdf"
tag = "v0.15.0"
use = ["asdf.sh", "completions/asdf.zsh"]

# -------------------------------------------------------------------
# ohmyzsh/ohmyzsh plugin: ssh-agent
# -------------------------------------------------------------------
[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = [
  "ssh-agent/*.plugin.zsh",
]

# -------------------------------------------------------------------
# zsh-users/zsh-history-substring-search
# -------------------------------------------------------------------
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
use = ["zsh-history-substring-search.zsh"]

# -------------------------------------------------------------------
# junegunn/fzf pinned to v0.58.0 + separate bin injection
# -------------------------------------------------------------------
# 1) Main clone (sources, scripts, etc.)
[plugins."fzf-clone"]
github = "junegunn/fzf"
tag = "v0.58.0"
use = ["shell/completion.zsh", "shell/key-bindings.zsh", "install"]
apply = ['fzf-install', 'fzf-source']

[plugins."fzf-bin"]
github = "junegunn/fzf"
tag = "v0.58.0"
dir = "bin"
apply = ["PATH"]

# -------------------------------------------------------------------
# unixorn/fzf-zsh-plugin (kind:defer equivalent)
# -------------------------------------------------------------------
# [plugins."fzf-zsh-plugin"]
# github = "unixorn/fzf-zsh-plugin"
# apply = ["defer"]

# -------------------------------------------------------------------
# Aloxaf/fzf-tab
# -------------------------------------------------------------------
[plugins."fzf-tab"]
github = "Aloxaf/fzf-tab"
use = ["fzf-tab.plugin.zsh"]

# -------------------------------------------------------------------
# zdharma-continuum/fast-syntax-highlighting (kind:defer)
# -------------------------------------------------------------------
[plugins."fast-syntax-highlighting"]
github = "zdharma-continuum/fast-syntax-highlighting"
use = ["fast-syntax-highlighting.plugin.zsh"]
apply = ["defer"]

# -------------------------------------------------------------------
# zsh-users/zsh-autosuggestions (kind:defer)
# -------------------------------------------------------------------
[plugins."zsh-autosuggestions"]
github = "zsh-users/zsh-autosuggestions"
use = ["zsh-autosuggestions.zsh"]
apply = ["defer"]

# -------------------------------------------------------------------
# MichaelAquilina/zsh-autoswitch-virtualenv
# -------------------------------------------------------------------
[plugins."zsh-autoswitch-virtualenv"]
github = "MichaelAquilina/zsh-autoswitch-virtualenv"
use = ["autoswitch_virtualenv.plugin.zsh"]
