# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 300
scan_timeout = 15

[line_break]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[cmake]
disabled = true

[docker_context]
disabled = true

[elixir]
disabled = true

[golang]
disabled = true

[git_status]
stashed = ""

[git_commit]
tag_symbol = " "

[cmd_duration]
format = ""

[lua]
format = ""
disabled = true

[aws]
disabled = true

[terraform]
disabled = true

# Workaround for WSL + systemd: https://github.com/starship/starship/issues/4556
[container]
disabled = true
