session_name: salt
start_directory: ./
windows:
- window_name: salt
  layout: main-horizontal
  focus: true
  panes:
  - focus: True
  - pane
  - pane
  options:
    main-pane-height: 35
  start_directory: /etc/salt
- window_name: salt-state-configs
  layout: main-horizontal
  panes:
  - focus: True
  - pane
  - pane
  options:
    main-pane-height: 35
  start_directory: ~/workspace/salt-states-configs
- window_name: private
  layout: main-horizontal
  panes:
  - focus: True
  - pane
  - pane
  options:
    main-pane-height: 35
  start_directory: ~/workspace/salt-states-private
